apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nonononon-gitops
  description: This is GitOps manifest for nonononon   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nonononon
    janus-idp.io/tekton: nonononon 
    backstage.io/kubernetes-id: nonononon 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nonononon
